name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      
    - name: Configurar Git para nombres largos
      run: git config --system core.longpaths true

    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.7.2'

    - name: Restaurar paquetes
      run: nuget restore EventifyMe.sln

    - name: Compilar solución
      run: msbuild EventifyMe.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml

    - name: Publicar en Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./bin/Release/net472/publish
